arb-dir: lib/l10n         # Carpeta donde estarán los .arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/generated/l10n
output-class: AppLocalizations
nullable-getter: false
